# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 340edda38acf7151f5ed70013edcb19b3324d4156c27d13c933f4e1af31b46f0513f7426f24ad8443ffc2457a2cec28b76726b171f8e7fc8eeec3993ddea116a

test:
  secret_key_base: 99b6373e6a7dd7488885f7fb2d796874b3d75ede0e20a1cafdc1ba3ec4c029fc58d159cc06a9253bab95d778885bf92cdff5a8be9baa227354223202c5c90f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
